# .github/workflows/cd.yml
name: CD Pipeline

on:
  push:
    branches: [ main ]
    tags:
      - 'v*'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build twine
        pip install -r requirements.txt
    - name: Build Docker image
      run: |
        docker build -t mlops-model:latest .
    - name: Register model to MLflow
      run: |
        python -m src.models.register_model
    # Additional deployment steps would go here, like:
    # - Deploying to cloud
    # - Updating model endpoints
    # - Notifying monitoring systems
